global using Mel.GitRepositoryReplicator.Infrastructure.ExtensionMethods;
global using Mel.GitRepositoryReplicator.CrossCuttingConcerns.ConstrainedTypes;
global using Mel.GitRepositoryReplicator.CrossCuttingConcerns.ErrorHandling;

