global using Mel.GitRepositoryReplicator.CrossCuttingConcerns.ErrorHandling;
global using Mel.GitRepositoryReplicator.CrossCuttingConcerns.ExtensionMethods;
global using Mel.GitRepositoryReplicator.CrossCuttingConcerns.ConstrainedTypes;
