namespace Mel.GitRepositoryReplicator.Application.UseCases;

public record ReplicateCodeRepositoryInput(
	CodeRepositoryId SourceRepositoryId,
	FolderPath TargetRepositoryPath,
	RepositoryName TargetRepositoryName,
	RepositoryRootNamespace TargetRepositoryRootNamespace,
	Language TargetRepositoryApiLanguage,
	Language TargetRepositoryMessagesLanguage,
	Language TargetRepositoryDocumentationLanguage,
	Language TargetRepositoryCommitMessagesLanguage);
