global using Mel.GitRepositoryReplicator.Application.ExtensionMethods.cs;
global using Mel.GitRepositoryReplicator.CrossCuttingConcerns.ErrorHandling;
global using Mel.GitRepositoryReplicator.CrossCuttingConcerns.ConstrainedTypes;
